---
title: "Study file_w_F_vcf and sig4 linking tumors"
format: html
---

## Setup

```{r}
library(fastrc)
library(stringr)
library(glue)
library(dplyr)
library(data.table)

indir1 = "~/MEGA/important_mut_sig_data/fmh-unfiltered_vcfs"

sigFfile = "DRUP01030028T"
sig4file = "CPCT02100089T"

sfpath = glue("{sigFfile}_annotvcf.csv")
s4path = glue("{sig4file}_annotvcf.csv")
mousepath = "../Manuscript_data/Reijn.mouse.vcfs.with.annotation.txt"
wt_cell_path = "../Manuscript_data/Reijn_wt_cell_annot.vcf"
mut_cell_path = "../Manuscript_data/Reijn_mut_cell_annot.vcf"
```

## Read annotated InsDelF and InsDel4 linking tumor VCFs

```{r}
#| label: read-tumor-vcfs
# The .annotated.indel.vcf.gz files are pre-annotated TSVs
sf_gz <- file.path(indir1, paste0(sigFfile, ".annotated.indel.vcf.gz"))
s4_gz <- file.path(indir1, paste0(sig4file, ".annotated.indel.vcf.gz"))

if (!file.exists(sfpath)) {
  file_w_F_vcf <- fread(sf_gz)
  fwrite(file_w_F_vcf, sfpath)
}

if (!file.exists(s4path)) {
  file_w_4_vcf <- fread(s4_gz)
  fwrite(file_w_4_vcf, s4path)
}
```

## Read annotated VCFs

```{r}
fread(sfpath) -> file_w_F_vcf
fread(s4path) -> file_w_4_vcf
fread(mousepath) -> mousevcf
fread(wt_cell_path) -> wt_cellvcf
fread(mut_cell_path) -> mut_cellvcf
```

## Helper functions

```{r}
del_counts = function(annotvcf) {
  annotvcf %>%
    dplyr::filter(nchar(ins_or_del_seq) >= 2) %>%
    dplyr::filter(ins_or_del == "d") %>%
    dplyr::filter(R <= 9) %>%
    dplyr::count(short_visual, Koh_476) %>%
    dplyr::arrange(desc(n)) %>%
    dplyr::mutate(vis2 = gsub("\\}", "", gsub("\\{", "", short_visual))) %>%
    dplyr::mutate(del_seq = str_extract(vis2, "(?<=<)[^>]+(?=>)")) %>%
    dplyr::mutate(hasmh = grepl("\\{", short_visual)) -> foo
  return(foo)
}
```

```{r}
normit = function(xx) {
  xx %>%
    mutate(post = gsub(".*>", "", vis2)) %>%
    mutate(post = gsub("\\[", "", post)) %>%
    mutate(clean = gsub("]", "", gsub("[><\\[]", "", vis2))) %>%
    mutate(
      norm = ifelse(substr(clean, 1, 1) %in% c("A", "G"), fast_rc(clean), clean)
    ) %>%
    mutate(prop_n = n / sum(xx$n)) %>%
    select(Koh_476, norm, n, prop_n, Koh_476, short_visual)
}
```

## Summarize and normalize deletion types

```{r}
file_w_F_vcfsummary = del_counts(file_w_F_vcf)

normit(file_w_F_vcfsummary) -> normF

file_w_4_vcfsummary = del_counts(file_w_4_vcf)

normit(file_w_4_vcfsummary) -> norm4

del_counts(mousevcf) -> mouse_summary

normit(mouse_summary) -> norm_mouse

del_counts(wt_cellvcf) -> wt_cell_summary

normit(wt_cell_summary) -> wt_cell_norm

del_counts(mut_cellvcf) -> mut_cell_summary

normit(mut_cell_summary) -> mut_cell_norm

```

## Counts and relative count of different deletion types

```{r}
#| results: asis

all_norm <- bind_rows(
  normF %>% mutate(source = "sigF tumor"),
  norm_mouse %>% mutate(source = "mouse"),
  mut_cell_norm %>% mutate(source = "mutated cells"),
  wt_cell_norm %>% mutate(source = "WT cells"),
  norm4 %>% mutate(source = "sig4 tumor")
)

for (deltype in c(
  "Del2:M1",
  "Del2:U2:R2",
  "Del3:U3:R2",
  "Del4:U4:R2",
  "Del3:M2",
  "Del4:M3",
  "Del4:M2"
)) {
  cat("###", deltype, "\n\n")
  all_norm %>%
    filter(Koh_476 == deltype) %>%
    select(-Koh_476) %>%
    mutate(prop_n = sprintf("%.4f", prop_n), n = as.character(n)) %>%
    tidyr::pivot_wider(
      id_cols = c(norm, short_visual),
      names_from = source,
      values_from = c(n, prop_n),
      names_glue = "{source} {.value}",
      names_vary = "slowest",
      values_fill = ""
    ) %>%
    {
      wide <- .
      prop_cols <- grep("prop_n", names(wide), value = TRUE)
      total <- setNames(as.list(rep("", ncol(wide))), names(wide))
      total[["norm"]] <- "**Total**"
      for (pc in prop_cols) {
        vals <- as.numeric(wide[[pc]][wide[[pc]] != ""])
        total[[pc]] <- sprintf("%.4f", sum(vals, na.rm = TRUE))
      }
      bind_rows(wide, tibble(!!!total))
    } %>%
    knitr::kable() %>%
    print()
  cat("\n\n")
}
```




## Fraction of AG dinucleotide deletions

```{r}
normF %>%
  filter(grepl("T.T", norm)) %>%
  select(n) %>%
  sum() %>%
  '/'(sum(normF$n))
norm4 %>%
  filter(grepl("T.T", norm)) %>%
  select(n) %>%
  sum() %>%
  '/'(sum(norm4$n))
```
