---
title: "Study file_w_F_vcf and sig4 linking tumors"
format: html
---

## Setup

```{r}
library(stringr)
library(ICAMS)
library(glue)
library(dplyr)
library(data.table)

indir1 = "~/MEGA/important_mut_sig_data/fmh-unfiltered_vcfs"

sigFfile = "DRUP01030028T"
sig4file = "CPCT02100089T"

sfpath = glue("{sigFfile}_annotvcf.csv")
s4path = glue("{sig4file}_annotvcf.csv")
mousepath = "../Manuscript_data/Reijn.mouse.vcfs.with.annotation.txt"
wt_cell_path = "../Manuscript_data/Reijn_wt_cell_annot.vcf"
mut_cell_path = "../Manuscript_data/Reijn_mut_cell_annot.vcf"
```

## Annotate InsDelF linking tumor VCF

```{r}
file1 = dir(indir1, pattern = sigFfile, full.names = TRUE) # This is the InsdelF linking Tumor

if (!file.exists(sfpath)) {
  vcf <- ICAMS::ReadVCFs(file1, filter.status = "PASS")
  F <-
    AnnotateIDVCF(
      vcf[[1]],
      ref.genome = "hg19",
      explain_indels = 1
    )
  file_w_F_vcf = F[[1]]
  file_w_F_vcf %>% fwrite(sfpath)
}
```

## Annotate InsDel4 linking tumor VCF

```{r}
if (!file.exists(s4path)) {
  file2 = dir(indir1, pattern = sig4file, full.names = TRUE) # This is the Insdel4 linking tumor
  vcf <- ICAMS::ReadVCFs(file2, filter.status = "PASS")
  library(ICAMS)
  F <-
    AnnotateIDVCF(
      vcf[[1]],
      ref.genome = "hg19",
      explain_indels = 1
    )
  file_w_4_vcf = F[[1]]
  file_w_4_vcf %>% fwrite(s4path)
}
```

## Read annotated VCFs

```{r}
fread(sfpath) -> file_w_F_vcf
fread(s4path) -> file_w_4_vcf
fread(mousepath) -> mousevcf
fread(wt_cell_path) -> wt_cellvcf
fread(mut_cell_path) -> mut_cellvcf
```

## Helper functions

```{r}
del2_counts = function(annotvcf) {
  annotvcf %>%
    dplyr::filter(nchar(ins_or_del_seq) == 2) %>%
    dplyr::filter(ins_or_del == "d") %>%
    dplyr::count(short_visual, Koh_476) %>%
    dplyr::arrange(desc(n)) %>%
    dplyr::mutate(vis2 = gsub("\\}", "", gsub("\\{", "", short_visual))) %>%
    dplyr::mutate(dinuc = str_extract(vis2, "(?<=<).{2}(?=>)")) %>%
    dplyr::mutate(hasmh = grepl("\\{", short_visual)) -> foo
  return(foo)
}
```

```{r}
normit = function(xx) {
  xx %>%
    mutate(post = gsub(".*>", "", vis2)) %>%
    mutate(post = gsub("\\[", "", post)) %>%
    mutate(clean = gsub("]", "", gsub("[><\\[]", "", vis2))) %>%
    mutate(
      norm = ifelse(substr(clean, 1, 1) %in% c("C", "T"), revc(clean), clean)
    ) %>%
    mutate(prop_n = n / sum(xx$n)) %>%
    selelct(Koh_476, norm, n, prop_n, Koh_476, short_visual)
}
```

## Summarize and normalize deletion types

```{r}
file_w_F_vcfsummary = del2_counts(file_w_F_vcf)

normit(file_w_F_vcfsummary) -> normF

file_w_4_vcfsummary = del2_counts(file_w_4_vcf)

normit(file_w_4_vcfsummary) -> norm4

del2_counts(mousevcf) -> mouse_summary

normit(mouse_summary) -> norm_mouse

del2_counts(wt_cellvcf) -> wt_cell_summary

normit(wt_cell_summary) -> wt_cell_norm

del2_counts(mut_cellvcf) -> mut_cell_summary

normit(mut_cell_summary) -> mut_cell_norm

```

## Counts and relative count of different deletion types

```{r}

for (deltype in c(
  "Del2:M1",
  "Del3:M2",
  "Del4:M3",
  "Del2:U2:R2",
  "Del3:U3:R2",
  "Del4:U4:r2"
)) {
  mut_cell_norm %>% filter(Koh_476 == deltype)
  wt_cell_norm %>% filter(Koh_476 == deltype)
  norm_mouse %>% filter(Koh_476 == deltype)
  norm4 %>% filter(Koh_476 == deltype)
  normF %>% filter(Koh_476 == deltype)
}
```




## Fraction of AG dinucleotide deletions

```{r}
normF %>%
  filter(grepl("AG", norm)) %>%
  select(n) %>%
  sum() %>%
  '/'(sum(normF$n))
norm4 %>%
  filter(grepl("AG", norm)) %>%
  select(n) %>%
  sum() %>%
  '/'(sum(norm4$n))
```
