---
title: "ID89 and ID83 vignette"
output:
  html_document: default
  pdf_document: default
date: "`r Sys.Date()`"
---

```{r libraries, include=FALSE} 
library(magrittr)
library(indelsig.tools.lib)
library(gridExtra)
library(data.table)
library(ICAMS)
library(mSigPlot)
library(data.table)
library(ggplot2)
```

```{r other-globals}
data_dir = "../Manuscript_data/"
plot476_base_size = 18
plto476_simplify_labels = FALSE
plot476_height = unit(4, "in")
plot89_height = unit(3, "in")

print(getwd())
```

```{r get-data-1}
ID89_ID83_connection_example <- fread(file.path(
  data_dir,
  "89type_to_83type_connection.tsv"
))
colnames(ID89_ID83_connection_example) <- c(
  "ID89_signature",
  "example_catalog",
  "ID83_signature",
  "type746_signature_id",
  "type476_where_extracted"
)


to.plot.WGS_PCAWG_HMF_indels.catalog <- fread(file.path(
  data_dir,
  "Liu_et_al_83_type_spectra.tsv"
)) # "justified.HMF.PCAWG.COSMIC83catalog.txt")

to.plot.WGS_PCAWG_HMF_indels.catalog <- ICAMS::as.catalog(
  to.plot.WGS_PCAWG_HMF_indels.catalog[, -1],
  infer.rownames = T
)
to.plot.WGS_PCAWG_HMF_indels.catalog.no.polyT <- to.plot.WGS_PCAWG_HMF_indels.catalog
to.plot.WGS_PCAWG_HMF_indels.catalog.no.polyT[c(12, 24), ] <- 0
```

```{r setup2, include = FALSE}

to.plot.all.signatures.final <- as.data.frame(fread(file.path(
  data_dir,
  "Liu_et_al_final_83_type_signatures.tsv"
))) # "/transfer/LiuMo_data/Working/DBS_Indel_Signature/For_manuscript_reference/PCAWG.HMF.ID83.signature.txt"))
to.plot.all.signatures.final <- to.plot.all.signatures.final[, -1]
to.plot.all.signatures.final <- ICAMS::as.catalog(
  to.plot.all.signatures.final,
  infer.rownames = T,
  catalog.type = "counts.signature"
)
```

```{r setup3, include = FALSE}

## replace with

# read.delim(file.path(
#   data_dir,
#   "Liu_et_al_final_89_type_signatures.tsv"
# ), row.names = 1)

to.plot.all.ID89.signatures.final <- as.data.frame(fread(file.path(
  data_dir,
  "Liu_et_al_final_89_type_signatures.tsv"
)))
row.names(
  to.plot.all.ID89.signatures.final
) <- to.plot.all.ID89.signatures.final[, 1] # Use the first column as row names
# Optionally, remove the first column from the data table
to.plot.all.ID89.signatures.final <- to.plot.all.ID89.signatures.final[, -1]


to.plot.all.ID89.catalogs <- as.data.frame(data.table::fread(
  file.path(data_dir, "Liu_et_al_89_type_spectra.tsv")
))
row.names(to.plot.all.ID89.catalogs) <- to.plot.all.ID89.catalogs[, 1] # Use the first column as row names

# Optionally, remove the first column from the data table
to.plot.all.ID89.catalogs <- to.plot.all.ID89.catalogs[, -1]
```

```{r setup4, include = FALSE}

# ID89.mSigAct.assignment <- readRDS("./ID89.mSigAct.assignment.rds")
ID89.mSigAct.assignment <- read.delim(
  file.path(
    data_dir,
    "Liu_et_al_89_type_signature_assignments.tsv"
  ),
  check.names = FALSE # Prevents e.g. foo::SP9999 -> foo..SP9999
)
```

```{r setup5}
final.Koh476.signatures <- as.data.frame(data.table::fread(
  file.path(
    data_dir,
    "Liu_et_al_final_476_type_signatures.tsv"
  )
))
row.names(final.Koh476.signatures) <- final.Koh476.signatures[, 1] # Use the first column as row names

# Optionally, remove the first column from the data table
final.Koh476.signatures <- final.Koh476.signatures[, -1]

to.plot.all.ID476.catalogs <- as.data.frame(data.table::fread(
  file.path(data_dir, "Liu_et_al_476_type_spectra.tsv")
))
row.names(to.plot.all.ID476.catalogs) <- to.plot.all.ID476.catalogs[, 1] # Use the first column as row names

# Optionally, remove the first column from the data table
to.plot.all.ID476.catalogs <- to.plot.all.ID476.catalogs[, -1]

```


```{r load-helpers}
# Load helper functions for modular processing
source("vignette_helpers.R")
```

```{r precompute-all-data}
# APPROACH 3: Pre-compute all signature data before rendering
# This separates computation from plotting, making debugging easier

all_signature_data <- lapply(seq_len(nrow(ID89_ID83_connection_example)), function(i) {
  compute_signature_data(
    ID89signature = ID89_ID83_connection_example$ID89_signature[i],
    catalog = ID89_ID83_connection_example$example_catalog[i],
    ID83signature = ID89_ID83_connection_example$ID83_signature[i],
    ID89_signatures = to.plot.all.ID89.signatures.final,
    ID89_catalogs = to.plot.all.ID89.catalogs,
    ID83_signatures = to.plot.all.signatures.final,
    ID83_catalogs = to.plot.WGS_PCAWG_HMF_indels.catalog,
    ID83_catalogs_no_polyT = to.plot.WGS_PCAWG_HMF_indels.catalog.no.polyT,
    ID476_signatures = final.Koh476.signatures,
    ID476_catalogs = to.plot.all.ID476.catalogs,
    assignment_matrix = ID89.mSigAct.assignment
  )
})

# Name the list for easier debugging
names(all_signature_data) <- ID89_ID83_connection_example$ID89_signature
```

```{r validate-precomputed-data}
# Optional: Validate all data was computed correctly before rendering
# This catches computation errors before they appear in plot rendering
for (i in seq_along(all_signature_data)) {
  sig <- all_signature_data[[i]]
  if (is.na(sig$cosine89)) {
    warning(paste("Missing cosine89 for:", sig$ID89signature))
  }
  if (is.na(sig$cosine83)) {
    warning(paste("Missing cosine83 for:", sig$ID89signature))
  }
}
```

```{r render-all-sections, fig.width=19, fig.height=4, echo=FALSE, results="asis", warning=FALSE}
# APPROACH 2: Use knit_child with a template for each signature section
# Each iteration uses the child template, isolating errors to specific sections

for (i in seq_along(all_signature_data)) {
  # Set sig_data in the environment for the child template
  sig_data <- all_signature_data[[i]]

  # Render the child template for this signature
  # Errors will reference _signature_section.Rmd with specific line numbers
  res <- knitr::knit_child(
    "_signature_section.Rmd",
    envir = environment(),
    quiet = TRUE
  )
  cat(res, sep = "\n")
}
```


