---
title: "MSI Study"
format: html
---

```{r}
#| label: loaddata

source(here::here("code/read_annotated_vcf.R"))
source(here::here("code/filter_vcf_by_mutation_type.R"))

# sample_id <- "Colon::CPCT02170035T"

# sample_id <- "Colon::DRUP01050002T"

sample_id <- "Colon::CPCT02050279T" # OK


filtered_vcf <- filter_vcf_by_mutation_type(sample_id, "Del2:U1:R(5,9)")
filtered_vcf <- filter_vcf_by_mutation_type(sample_id, "Del3:U1:R(5,9)")
filtered_vcf <- filter_vcf_by_mutation_type(sample_id, "Del2:U2:R(5,9)")
filtered_vcf <- filter_vcf_by_mutation_type(sample_id, "A[T:R(9,)]A")
```

```{r}
#| label: counteach2del

del_seq_counts <- filtered_vcf |>
  dplyr::count(ins_or_del_seq)
del_seq_context_counts <- filtered_vcf |>
  dplyr::count(ins_or_del_seq, R_outside_ins_or_del_seq, short_visual) |>
  dplyr::arrange(desc(n))
```

```{r}
spectra <- read.delim(
  here::here("Manuscript_data/Liu_et_al_476_type_spectra.tsv"),
  sep = '\t',
  check.names = FALSE,
  row.names = 1
)
sample_spectrum <- spectra[, sample_id, drop = FALSE]
```

```{r}
#| label: readrawvcf

raw_vcf <- read_annotated_vcf(sample_id)
raw_vcf <- dplyr::filter(raw_vcf, FILTER == "PASS")
```

```{r}
#| label: delTlen_dist
raw_vcf |> dplyr::filter(grepl("Del\\T", Koh_476))
polyt |> dplyr::filter(grepl("T", Koh_476)) -> deltonly
```


```{r}
source(here::here("code/Generate_Koh89_Koh476_catalog_0121.R"))

raw_vcf$sample_id = 'X'
computed = GenerateKoh476CatalogfromAnnotateVcf(raw_vcf, 'sample_id')

```

